//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgImage
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int ImageId { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
